apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - sfera.xn--80ae3aih3a1c.xn--p1ai
      secretName: sfera.xn--80ae3aih3a1c.xn--p1ai
  rules:
    - host: sfera.xn--80ae3aih3a1c.xn--p1ai
      http:
        paths:
        - backend:
            serviceName: app
            servicePort: 8000
          path: /
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: stiletv/test:tagname
        ports:
        - containerPort: 8000
